name: Linux
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
jobs:
  ci:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cxx: g++-10
            config: Release
          - cxx: g++-10
            config: Debug
          - cxx: clang++-12
            config: Release
          - cxx: clang++-12
            config: Debug
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: jurplel/install-qt-action@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            libasound2-dev \
            ninja-build
      - name: Run CMake
        env:
          CXX: ${{ matrix.cxx }}
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DCMAKE_PREFIX_PATH=${Qt5_DIR} \
            -DAULOS_BENCHMARKS=${{ matrix.config != 'Debug' && 'ON' || 'OFF' }}
      - name: Build
        run: |
          cmake --build build
