name: Windows
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
jobs:
  ninja:
    name: Ninja
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - config: Release
          - config: Debug
      fail-fast: false
    env:
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - uses: jurplel/install-qt-action@v2
      - name: Install dependencies
        run: |
          cinst ninja
      - name: Run CMake
        run: |
          cmake -S . -B build `
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} `
            -DCMAKE_PREFIX_PATH=$Env:Qt5_DIR `
            -DAULOS_STUDIO_INSTALLER=ON
      - name: Build
        run: |
          cmake --build build
      - name: Build installer
        run: |
          cmake --build build --target studio_installer
  vs:
    name: VS
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - config: Release
          - config: Debug
      fail-fast: false
    env:
      CMAKE_GENERATOR: Visual Studio 17 2022
      CMAKE_GENERATOR_PLATFORM: x64
    steps:
      - uses: actions/checkout@v2
      - uses: jurplel/install-qt-action@v2
      - name: Install dependencies
        run: |
          cinst ninja
      - name: Run CMake
        run: |
          cmake -S . -B build `
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\install" `
            -DCMAKE_PREFIX_PATH=$Env:Qt5_DIR `
            -DAULOS_STUDIO_INSTALLER=ON
      - name: Build
        run: |
          cmake --build build --config ${{ matrix.config }} --parallel -- /nologo
      - name: Build installer
        run: |
          cmake --build build --config ${{ matrix.config }} --target studio_installer -- /nologo
